New idea

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,5 +1,5 @@
 name: "Generate KiCad files"
-description: "Generate KiCad files like a pdf schematic, bom files, etc."
+description: "Generate KiCad files like a PDF schematic, BOM files, etc."
 branding:
   icon: "cpu"
   color: "yellow"
@@ -23,14 +23,14 @@ inputs:
     required: true
   layers:
     description: >
-      The layers that need to be exported in a comma separated list. Example: "F.Cu,B.cu". If no layers are given, all layers are exported.
+      The layers that need to be exported in a comma-separated list. Example: "F.Cu,B.Cu". If no layers are given, all layers are exported.
       This input can be used when exporting the following types:
       - pcb_gerbers
       - pcb_gerbers_drill
   black-and-white:
     description: >
       Export schematic in black and white.
-      The black-and-white option be used when exporting the following types:
+      This option can be used when exporting the following types:
       - schematic_pdf
       - schematic_svg
     default: false
@@ -38,13 +38,62 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: "Copy export-files script"
-      run: |
-        cp ${{ github.action_path }}/export-files.sh /usr/local/bin/
-        chmod +x /usr/local/bin/export-files.sh
-      shell: bash
+    - name: Pre-pull Docker Image
+      run: docker pull docker.io/kicad/kicad:8.0
 
     - id: export-files
-      name: "Export files."
-      run: export-files.sh --type "${{ inputs.type }}" --layers "${{ inputs.layers }}" --black-and-white "${{ inputs.black-and-white }}" "${{ inputs.file }}"
-      shell: bash
+      name: Export KiCad Files Using Docker
+      run: |
+        mkdir -p generated-files
+        docker run --rm \
+          -v "${{ github.workspace }}:/workspace" \
+          -w "/workspace" \
+          docker.io/kicad/kicad:8.0 \
+          /bin/bash -c "
+            export FILE=${{ inputs.file }}
+            export TYPE=${{ inputs.type }}
+            export LAYERS=${{ inputs.layers }}
+            export BLACK_AND_WHITE=${{ inputs.black-and-white }}
+            
+            OUTPUT_DIR=\"/workspace/generated-files\"
+
+            case \"$TYPE\" in
+              schematic_pdf)
+                kicad-cli sch export pdf --black-and-white=$BLACK_AND_WHITE \"$FILE\" -o \"$OUTPUT_DIR/schematic.pdf\"
+                ;;
+              schematic_svg)
+                kicad-cli sch export svg --black-and-white=$BLACK_AND_WHITE \"$FILE\" -o \"$OUTPUT_DIR/schematic.svg\"
+                ;;
+              schematic_bom)
+                kicad-cli sch export bom \"$FILE\" -o \"$OUTPUT_DIR/bom.csv\"
+                ;;
+              schematic_netlist)
+                kicad-cli sch export netlist \"$FILE\" -o \"$OUTPUT_DIR/netlist.net\"
+                ;;
+              pcb_step)
+                kicad-cli pcb export step \"$FILE\" -o \"$OUTPUT_DIR/board.step\"
+                ;;
+              pcb_pos)
+                kicad-cli pcb export pos \"$FILE\" -o \"$OUTPUT_DIR/pos.csv\"
+                ;;
+              pcb_gerbers)
+                kicad-cli pcb export gerbers --layers=\"$LAYERS\" \"$FILE\" -o \"$OUTPUT_DIR/gerbers\"
+                ;;
+              pcb_drill)
+                kicad-cli pcb export drill \"$FILE\" -o \"$OUTPUT_DIR/drill.drl\"
+                ;;
+              pcb_gerbers_drill)
+                kicad-cli pcb export gerbers-drill --layers=\"$LAYERS\" \"$FILE\" -o \"$OUTPUT_DIR/gerbers-drill\"
+                ;;
+              *)
+                echo \"Invalid type specified\"
+                exit 1
+                ;;
+            esac
+          "
+
+    - name: Upload Exported Files
+      uses: actions/upload-artifact@v4
+      with:
+        name: "KiCad Generated Files"
+        path: "generated-files"
